In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
df = pd.read_csv('../../Datasets/digit-recognizer-train.csv')

In [3]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf1 = LogisticRegression(max_iter=1000)
clf2 = DecisionTreeClassifier()

clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

In [ ]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9145238095238095
Accuracy of Decision Trees 0.8519047619047619

In [ ]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [ ]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  745    0   17    9    7   19    6    1   10    7
1    0  904   10   12   10    3    6    5   10    2
2    7   20  670   33   18   15   18   18   22    8
3    7   12   33  697    5   42   10   11   31   16
4    5    4    9   11  729   14   14   10   15   45
5   13    6    8   39    6  584   17   11   26   19
6   10    1    6    5   12   21  765    0   13    6
7    3   10   19   15    9    6    1  775   14   21
8    9   11   23   37   17   36   15    8  615   22
9    8    4    6   19   51   18    7   24   25  672

In [ ]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [ ]:
precision_score(y_test,y_pred1,average='weighted')

0.9142150713630827

In [ ]:
recall_score(y_test,y_pred1,average='weighted')

0.9145238095238095

In [ ]:
f1_score(y_test,y_pred1,average='weighted')

0.9142794994052751

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400